config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home" 

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  devise_for :users
  resources :users
  resources :books
  resources :brands
  resources :categories
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :brand
  belongs_to :category
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :books
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

  validates :name, presence: true, length: {minimum: 3}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.paginate page: params[:page], per_page: 10
  end

  def show
    @book = Book.find params[:id]
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.paginate page: params[:page], per_page: 10
  end
  
  def create
  end

  def show
    @brand = Brand.find params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate page: params[:page], per_page: 5
  end

  def show
    @category = Category.find_by_id params[:id]
    @books = @category.books
    @categories = Category.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, except: :show

  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def show
    @user = User.find params[:id]
    unless current_user.admin?
      redirect_to :back, alert: "Access denied."
    end
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes secure_params
      redirect_to users_path, notice: "User updated."
    else
      redirect_to users_path, alert: "Unable to update user."
    end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to users_path, notice: "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, alert: "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit :role
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
require 'rubygems'
require 'pdf/reader'

module BooksHelper
  def image(book)
    image_tag(book.image, alt: book.name, class: "gravatar")
  end

  def read_book(book)
    receiver = PDF::Reader::RegisterReceiver.new
    filename = "app/assets/book/NienLuan.pdf"

    content = ""
    reader = PDF::Reader.new(filename) 
    reader.pages.each do |page|
      content << page.text
    end
    return content
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_book.html.erb
<tr>
  <td><%= book.id %></td>
  <td><%= link_to image(book), book %></td>
  <td><%= book.name %></td>
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.desc %></td>
  <td><%= book.link %></td>
</tr>

app/views/books/index.html.erb
<h1>All Books</h1>
<%= will_paginate @books %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>No.</th>
      <th>Image</th>
      <th>Name</th>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Content</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <%= render book %>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div style="padding: 20px;">
  <ul class="nav nav-tabs" id="myTab">
    <li><a data-toggle="tab" href="#info">Info Book</a></li>
    <li><a data-toggle="tab" href="#reader">Reade</a></li>
  </ul>
  <div class="tab-content">
    <div id="info" class="tab-pane fade in active">
        <div class="row" >
          <div class="col-md-4">
            <h1><%= @book.name %></h1><br>by <%= @book.author %><br>
            About the book :<br><h4><%= @book.desc %></h4><br>
            <%= link_to 'ADD LIBRARY', "#", class:"btn btn-warning" %>
          </div>
          <div class="col-md-4">
            <%= image_tag(@book.image, alt: @book.name, class: "image_info-book") %>
          </div>
      </div>
    </div>
    <div id="reader" class="tab-pane fade" style="height: 500px;overflow: scroll;">
      <p><%= read_book @book %></p>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){ 
    $("#myTab li:eq(0) a").tab('show');
  });
</script>

app/views/brands/_brand.html.erb
<div>
  <%= image_tag(brand.image, alt: brand.name, class: "book-image") %>
  <%= brand.name %>
</div>

app/views/brands/create.html.erb
<h1>Brands#create</h1>
<p>Find me in app/views/brands/create.html.erb</p>

app/views/brands/show.html.erb
<ul>
  <% @brands.each do |brand| %>
    <li><%= render brand %></li>
  <% end %>
</ul>

app/views/categories/index.html.erb
<% provide :title, "All Categories" %>
<h1>All Categories</h1>
<ul class="categories">
  <% @categories.each do |category| %>
    <li><%= category.name %></li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <ul class="nav navbar-nav pull-right">
    <li><%= link_to "About",   about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <li><%= link_to "Help",    help_path %></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'Book', books_path %></li>
  <li><%= link_to 'Category', categories_path %></li>
  <li><%= link_to 'Admin', users_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Brs07</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "home.ico" %>
  </head>

  <body>
    <header><%= render 'layouts/header' %></header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </main>
    <footer><%= render 'layouts/footer' %></footer>
  </body>

</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<center>
  <h2>This is about page</h2>
</center>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<center>
  <h2>This is contact page</h2>
</center>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<center>
  <h2>This is help page</h2>
</center>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% unless user_signed_in? %>
  <center>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag("03.jpg", :alt => "rss feed") %>
          <div class="carousel-caption">
            Chu Van Hieu
          </div>
        </div>
        <div class="item">
           <%= image_tag("02.jpg", :alt => "rss feed") %>
          <div class="carousel-caption">
            Do Cong Thanh
          </div>
        </div>

        <div class="item">
           <%= image_tag("01.jpg", :alt => "rss feed") %>
          <div class="carousel-caption">
            Trinh Minh Tam
          </div>
        </div>

        <div class="item">
           <%= image_tag("04.jpeg", :alt => "rss feed") %>
          <div class="carousel-caption">
            Book reviewing system
          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" 
         role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" 
         role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <h1>Welcome to Book Reviewing System</h1>
    <div class="btn-group btn-group-lg">
        <%= link_to 'Sign up now', new_user_registration_path %>
    </div>
  </center>
<% else %>
  <h2>This is home page</h2>
<% end %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', class: 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to_unless(user == current_user, "Delete user", user_path(user), data: {confirm: "Are you sure?"}, method: :delete, class: 'button-xs') %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users: <%= User.count %> registered</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>